name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Installando prerequisiti
      run: |
        sudo apt-get update
        sudo apt-get -y install python3
    - name: Build project
      env:
        Clash_of_clans_API_token: ${{ secrets.CLASH_OF_CLANS_API_TOKEN }}
        Bot_token: ${{ secrets.BOT_TOKEN }}
      run: |
        python3 main.py