name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installando prerequisiti
      run: |
        sudo apt-get update
        sudo apt-get -y install python3
    - name: Build project
      run: |
        python3 main.py